on:
  push:
    branches: [main, develop]

name: R-CMD-Check

jobs:
  R-CMD-Check:
    runs-on: ubuntu-22.04

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: '4.3.1'}
          - {os: ubuntu-latest,   r: '4.2.3'}

    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_KEEP_PKG_SOURCE: yes
      # CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # HCA_DB_PWD: ${{ secrets.HCA_DB_PWD }}
      # PACKAGEMANAGER_TOKEN: ${{ secrets.PACKAGEMANAGER_TOKEN }}
      # PACKAGEMANAGER_ADDRESS: ${{ secrets.PACKAGEMANAGER_ADDRESS }}


    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: false
          Ncpus: 4

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
